### ISSUE TITLE
java.lang.NullPointerException when executing PiG

### ISSUE THREAD

**Issue by goldmann** [project-ncl/bacon#272]
```
[ERROR] - Something wrong happened: 
java.lang.NullPointerException: null
	at org.jboss.pnc.bacon.pig.Pig.lambdazsh(Pig.java:107)
	at org.jboss.pnc.bacon.common.cli.AbstractCommand.executeHelper(AbstractCommand.java:205)
	at org.jboss.pnc.bacon.pig.Pig.execute(Pig.java:104)
	at org.aesh.command.impl.operator.EndOperator.execute(EndOperator.java:41)
	at org.aesh.command.impl.Executions.execute(Executions.java:213)
	at org.aesh.command.impl.AeshCommandRuntime.executeCommand(AeshCommandRuntime.java:161)
	at org.jboss.pnc.bacon.cli.App.run(App.java:97)
	at org.jboss.pnc.bacon.cli.App.main(App.java:128)
```

**Comment by goldmann** [comment]
Probably related to: #271.

I'm calling it this way:

```
bacon pig run some-dir --configPath /some/other/dir
```

**Comment by michalszynkiewicz** [comment]
@goldmann what is your config? It seems something is missing.
I'll add some better exception for it.

**Comment by goldmann** [comment]
The `pig` section was missing. Thanks!

**Comment by michalszynkiewicz** [comment]
https://github.com/project-ncl/bacon/pull/273
