### ISSUE TITLE
Exception when a non-existent group config is requested

### ISSUE THREAD

**Issue by goldmann** [project-ncl/bacon#305]
```
bash-5.0$ bacon pnc group-config get 14030
[ERROR] - Something wrong happened: 
org.jboss.pnc.client.RemoteResourceException: null
	at org.jboss.pnc.client.GroupConfigurationClient.getSpecific(GroupConfigurationClient.java:103)
	at org.jboss.pnc.bacon.pnc.GroupConfigCli$Get.getSpecific(GroupConfigCli.java:155)
	at org.jboss.pnc.bacon.pnc.GroupConfigCli$Get.getSpecific(GroupConfigCli.java:150)
	at org.jboss.pnc.bacon.common.cli.AbstractGetSpecificCommand.lambda$execute$0(AbstractGetSpecificCommand.java:52)
	at org.jboss.pnc.bacon.common.cli.AbstractCommand.executeHelper(AbstractCommand.java:205)
	at org.jboss.pnc.bacon.common.cli.AbstractGetSpecificCommand.execute(AbstractGetSpecificCommand.java:51)
	at org.aesh.command.impl.operator.EndOperator.execute(EndOperator.java:41)
	at org.aesh.command.impl.Executions$ExecutionImpl.execute(Executions.java:213)
	at org.aesh.command.impl.AeshCommandRuntime.executeCommand(AeshCommandRuntime.java:161)
	at org.jboss.pnc.bacon.cli.App.run(App.java:97)
	at org.jboss.pnc.bacon.cli.App.main(App.java:128)
Caused by: javax.ws.rs.InternalServerErrorException: HTTP 500 Internal Server Error
	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.handleErrorStatus(ClientInvocation.java:234)
	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.extractResult(ClientInvocation.java:196)
	at org.jboss.resteasy.client.jaxrs.internal.proxy.extractors.BodyEntityExtractor.extractEntity(BodyEntityExtractor.java:62)
	at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invokeSync(ClientInvoker.java:151)
	at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invoke(ClientInvoker.java:112)
	at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientProxy.invoke(ClientProxy.java:76)
	at com.sun.proxy.$Proxy49.getSpecific(Unknown Source)
	at org.jboss.pnc.client.GroupConfigurationClient.getSpecific(GroupConfigurationClient.java:88)
	... 10 common frames omitted
```

**Comment by michalovjan** [comment]
@goldmann  This is a bug on PNC side (https://github.com/project-ncl/pnc/pull/3237). Bacon has nothing to do with this, it is innocent!!
