### ISSUE TITLE
PiG: If the build is not required to run, running release fails

### ISSUE THREAD

**Issue by goldmann** [project-ncl/bacon#316]
```
[INFO ] - Generating NVR list for /workDir/workspace/pnc-2.0/test-java/cpaas-test-java/cpaas-test-pig-project/target/cpaas-test-product-1.0.0.ER1/cpaas-1.0.0.ER1-maven-repository.zip and saving result to /workDir/workspace/pnc-2.0/test-java/cpaas-test-java/cpaas-test-pig-project/target/cpaas-test-product-1.0.0.ER1/extras/cpaas-1.0.0.ER1-nvr-list.txt
[ERROR] - Something wrong happened: 
java.lang.IllegalArgumentException: Resource koji-build-finder/config.json not found
	at org.jboss.pnc.bacon.pig.impl.utils.ResourceUtils.getResourceAsString(ResourceUtils.java:145)
	at org.jboss.pnc.bacon.pig.impl.utils.ResourceUtils.extractToStringWithFiltering(ResourceUtils.java:77)
	at org.jboss.pnc.bacon.pig.impl.utils.BuildFinderUtils.getKojiBuildFinderConfigFromResource(BuildFinderUtils.java:63)
	at org.jboss.pnc.bacon.pig.impl.utils.BuildFinderUtils.getKojiBuildFinderConfig(BuildFinderUtils.java:91)
	at org.jboss.pnc.bacon.pig.impl.utils.BuildFinderUtils.findBuilds(BuildFinderUtils.java:102)
	at org.jboss.pnc.bacon.pig.impl.utils.BuildFinderUtils.findBuilds(BuildFinderUtils.java:160)
	at org.jboss.pnc.bacon.pig.impl.nvr.NvrListGenerator.generateNvrList(NvrListGenerator.java:42)
	at org.jboss.pnc.bacon.pig.PigFacade.generateNvrList(PigFacade.java:212)
	at org.jboss.pnc.bacon.pig.PigFacade.release(PigFacade.java:198)
	at org.jboss.pnc.bacon.pig.Pig.doExecute(Pig.java:403)
	at org.jboss.pnc.bacon.pig.Pig.doExecute(Pig.java:395)
	at org.jboss.pnc.bacon.pig.Pig.lambdazsh(Pig.java:126)
	at org.jboss.pnc.bacon.common.cli.AbstractCommand.executeHelper(AbstractCommand.java:205)
	at org.jboss.pnc.bacon.pig.Pig.execute(Pig.java:115)
	at org.aesh.command.impl.operator.EndOperator.execute(EndOperator.java:41)
	at org.aesh.command.impl.Executions.execute(Executions.java:213)
	at org.aesh.command.impl.AeshCommandRuntime.executeCommand(AeshCommandRuntime.java:161)
	at org.jboss.pnc.bacon.cli.App.run(App.java:97)
	at org.jboss.pnc.bacon.cli.App.main(App.java:128)
```

**Comment by goldmann** [comment]
This stacktrace is returned even if the push to Brew succeeds which makes it a critical issue.

**Comment by goldmann** [comment]
@dwalluck Any idea?

**Comment by dwalluck** [comment]
It is supposed to find that file in the pig jar
```
$ jar tf ./pig/target/pig-1.0-SNAPSHOT.jar | grep config.json
koji-build-finder/config.json
```

The code ultimately called which fails is

```
InputStream resourceStream = ResourceUtils.class.getResourceAsStream("koji-build-finder/config.json");
```

**Comment by dwalluck** [comment]
As a workaround, there are two ways to override that file location. Set either the environment variable `KOJI_BUILD_FINDER_CONFIG` or the property `-Dkoji.build.finder.config` to a valid path to a `config.json` file and see if it works this way.

One can be found at `./pig/src/main/resources/koji-build-finder/config.json`. However, the resources location seems to do property replacement, but for the other two methods you must add valid URLs to that file, I think.

**Comment by dwalluck** [comment]
CC @michalszynkiewicz

**Comment by goldmann** [comment]
@dwalluck Does it work when you use `./cli/target/bacon.jar` via the bash wrapper?

**Comment by dwalluck** [comment]
The `bacon.jar` file also appears to contain inside of it the pig `koji-build-finder/config.json` as well as the default KBF `config.json` at the top level. So the file seems to exist. Could it be a class loader issue?

**Comment by rnc** [comment]
Ok I have a fix for this and am looking into producing a test.

**Comment by goldmann** [comment]
I don't think this should be closed.

**Comment by rnc** [comment]
@dwalluck I'm copying your comment to a separate issue as this is closed.
