### ISSUE TITLE
PiG: null host when specifying --tempBuild and --mode FORCE together

### ISSUE THREAD

**Issue by goldmann** [project-ncl/bacon#327]
```
$bacon pig run --tempBuild --mode FORCE /workDir/workspace/pnc-2.0/test-java/cpaas-test-java/cpaas-test-pig-project/config/cpaas/development
[INFO ] - Generating milestone for versionId ProductVersion(super=ProductVersionRef(id=234, version=1.0, attributes={BREW_TAG_PREFIX=cpaas-tp-1.7-pnc}), product=ProductRef(id=175, name=CPaaS Test Product, description=null, abbreviation=cpaas-tp, productManagers=null, productPagesCode=null), currentProductMilestone=ProductMilestoneRef(id=257, version=1.0.0.ER1, endDate=null, startingDate=2020-08-06T00:00:00Z, plannedEndDate=2020-08-07T00:00:00Z), productMilestones={257=ProductMilestoneRef(id=257, version=1.0.0.ER1, endDate=null, startingDate=2020-08-06T00:00:00Z, plannedEndDate=2020-08-07T00:00:00Z), 269=ProductMilestoneRef(id=269, version=1.0.1.DR1, endDate=null, startingDate=2020-08-12T00:00:00Z, plannedEndDate=2020-08-13T00:00:00Z)}, productReleases={}, groupConfigs={646=GroupConfigurationRef(id=646, name=CPAAS-TP-1.0)}, buildConfigs={2338=BuildConfigurationRef(id=2338, name=dcheung-test-cpaas.tp-cpaas-test-pnc-gradle-1.0.0, description=null, buildScript=gradle clean publish, scmRevision=master, creationTime=2020-08-12T19:44:50.882Z, modificationTime=2020-08-12T19:44:50.866Z, buildType=GRADLE, defaultAlignmentParams=--info -DdependencySource=REST -DrepoRemovalBackup=repositories-backup.xml -DignoreUnresolvableDependencies=true), 2315=BuildConfigurationRef(id=2315, name=cpaas.tp-cpaas-test-pnc-gradle-1.0.0, description=null, buildScript=gradle clean publish, scmRevision=master, creationTime=2020-08-06T08:54:20.323Z, modificationTime=2020-08-19T16:24:21.383Z, buildType=GRADLE, defaultAlignmentParams=--info -DdependencySource=REST -DrepoRemovalBackup=repositories-backup.xml -DignoreUnresolvableDependencies=true), 2336=BuildConfigurationRef(id=2336, name=cpaas.tp-cpaas-test-pnc-maven-1.x, description=null, buildScript=mvn -Dinsecure.repositories=WARN clean deploy, scmRevision=master, creationTime=2020-08-12T12:13:14.946Z, modificationTime=2020-08-12T12:13:25.174Z, buildType=MVN, defaultAlignmentParams=-DdependencySource=REST -DrepoRemovalBackup=repositories-backup.xml -DversionSuffixStrip= -DreportNonAligned=true)}) and milestone 1.0.0.ER1 in PNC
[INFO ] - Adding/updating build configurations
[INFO ] - Temporary build
[INFO ] - Temporary build
[INFO ] - Performing builds of build group 646 in PNC
[INFO ] - waiting for finish of group build 2030
...[INFO ] - group build finished successfully
[INFO ] - Generating maven repo for build group [CPAAS-TP-1.0]
[INFO ] -  - getting all artifacts and dependencies for [cpaas.tp-cpaas-test-pnc-gradle-1.0.0]
[INFO ] - Downloading null/cpaas/tp/cpaas-test-pnc-gradle/1.0.0.temporary-redhat-00001/cpaas-test-pnc-gradle-1.0.0.temporary-redhat-00001-javadoc.jar to /tmp/deliverable-generation3626954702738383063/maven-repository/cpaas/tp/cpaas-test-pnc-gradle/1.0.0.temporary-redhat-00001/cpaas-test-pnc-gradle-1.0.0.temporary-redhat-00001-javadoc.jar
[WARN ] - Failed to download null/cpaas/tp/cpaas-test-pnc-gradle/1.0.0.temporary-redhat-00001/cpaas-test-pnc-gradle-1.0.0.temporary-redhat-00001-javadoc.jar. Will reattempt without SSL certificate check
[WARN ] - Unable to download sources for GAV(packaging=jar, groupId=cpaas.tp, artifactId=cpaas-test-pnc-gradle, version=1.0.0.temporary-redhat-00001, scope=null, classifier=javadoc)
java.lang.RuntimeException: failed to download null/cpaas/tp/cpaas-test-pnc-gradle/1.0.0.temporary-redhat-00001/cpaas-test-pnc-gradle-1.0.0.temporary-redhat-00001-javadoc.jar to /tmp/deliverable-generation3626954702738383063/maven-repository/cpaas/tp/cpaas-test-pnc-gradle/1.0.0.temporary-redhat-00001/cpaas-test-pnc-gradle-1.0.0.temporary-redhat-00001-javadoc.jar
	at org.jboss.pnc.bacon.pig.impl.utils.FileDownloadUtils.downloadTo(FileDownloadUtils.java:93)
	at org.jboss.pnc.bacon.pig.impl.repo.ExternalArtifactDownloader.downloadExternalArtifact(ExternalArtifactDownloader.java:54)
	at org.jboss.pnc.bacon.pig.impl.repo.ExternalArtifactDownloader.downloadExternalArtifact(ExternalArtifactDownloader.java:44)
	at org.jboss.pnc.bacon.pig.impl.repo.RepoManager.lambda(RepoManager.java:146)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at org.jboss.pnc.bacon.pig.impl.repo.RepoManager.filterAndDownload(RepoManager.java:146)
	at org.jboss.pnc.bacon.pig.impl.repo.RepoManager.buildGroup(RepoManager.java:167)
	at org.jboss.pnc.bacon.pig.impl.repo.RepoManager.prepare(RepoManager.java:90)
	at org.jboss.pnc.bacon.pig.PigFacade.generateRepo(PigFacade.java:346)
	at org.jboss.pnc.bacon.pig.PigFacade.run(PigFacade.java:155)
	at org.jboss.pnc.bacon.pig.Pig.doExecute(Pig.java:244)
	at org.jboss.pnc.bacon.pig.Pig.doExecute(Pig.java:134)
	at org.jboss.pnc.bacon.pig.Pig.lambdazsh(Pig.java:126)
	at org.jboss.pnc.bacon.common.cli.AbstractCommand.executeHelper(AbstractCommand.java:205)
	at org.jboss.pnc.bacon.pig.Pig.execute(Pig.java:115)
	at org.aesh.command.impl.operator.EndOperator.execute(EndOperator.java:41)
	at org.aesh.command.impl.Executions.execute(Executions.java:213)
	at org.aesh.command.impl.AeshCommandRuntime.executeCommand(AeshCommandRuntime.java:161)
	at org.jboss.pnc.bacon.cli.App.run(App.java:97)
	at org.jboss.pnc.bacon.cli.App.main(App.java:128)
Caused by: org.apache.http.client.ClientProtocolException: null
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:187)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
	at org.jboss.pnc.bacon.pig.impl.utils.FileDownloadUtils.downloadWithClient(FileDownloadUtils.java:106)
	at org.jboss.pnc.bacon.pig.impl.utils.FileDownloadUtils.downloadTo(FileDownloadUtils.java:90)
	... 19 common frames omitted
Caused by: org.apache.http.ProtocolException: Target host is not specified
	at org.apache.http.impl.conn.DefaultRoutePlanner.determineRoute(DefaultRoutePlanner.java:71)
	at org.apache.http.impl.client.InternalHttpClient.determineRoute(InternalHttpClient.java:125)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	... 23 common frames omitted
[INFO ] - Downloading null/cpaas/tp/cpaas-test-pnc-gradle/1.0.0.temporary-redhat-00001/cpaas-test-pnc-gradle-1.0.0.temporary-redhat-00001.jar to /tmp/deliverable-generation3626954702738383063/maven-repository/cpaas/tp/cpaas-test-pnc-gradle/1.0.0.temporary-redhat-00001/cpaas-test-pnc-gradle-1.0.0.temporary-redhat-00001.jar
[WARN ] - Failed to download null/cpaas/tp/cpaas-test-pnc-gradle/1.0.0.temporary-redhat-00001/cpaas-test-pnc-gradle-1.0.0.temporary-redhat-00001.jar. Will reattempt without SSL certificate check
[ERROR] - Something wrong happened: 
java.lang.RuntimeException: failed to download null/cpaas/tp/cpaas-test-pnc-gradle/1.0.0.temporary-redhat-00001/cpaas-test-pnc-gradle-1.0.0.temporary-redhat-00001.jar to /tmp/deliverable-generation3626954702738383063/maven-repository/cpaas/tp/cpaas-test-pnc-gradle/1.0.0.temporary-redhat-00001/cpaas-test-pnc-gradle-1.0.0.temporary-redhat-00001.jar
	at org.jboss.pnc.bacon.pig.impl.utils.FileDownloadUtils.downloadTo(FileDownloadUtils.java:93)
	at org.jboss.pnc.bacon.pig.impl.repo.ExternalArtifactDownloader.downloadExternalArtifact(ExternalArtifactDownloader.java:54)
	at org.jboss.pnc.bacon.pig.impl.repo.ExternalArtifactDownloader.downloadExternalArtifact(ExternalArtifactDownloader.java:44)
	at org.jboss.pnc.bacon.pig.impl.repo.RepoManager.lambda(RepoManager.java:146)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at org.jboss.pnc.bacon.pig.impl.repo.RepoManager.filterAndDownload(RepoManager.java:146)
	at org.jboss.pnc.bacon.pig.impl.repo.RepoManager.buildGroup(RepoManager.java:167)
	at org.jboss.pnc.bacon.pig.impl.repo.RepoManager.prepare(RepoManager.java:90)
	at org.jboss.pnc.bacon.pig.PigFacade.generateRepo(PigFacade.java:346)
	at org.jboss.pnc.bacon.pig.PigFacade.run(PigFacade.java:155)
	at org.jboss.pnc.bacon.pig.Pig.doExecute(Pig.java:244)
	at org.jboss.pnc.bacon.pig.Pig.doExecute(Pig.java:134)
	at org.jboss.pnc.bacon.pig.Pig.lambdazsh(Pig.java:126)
	at org.jboss.pnc.bacon.common.cli.AbstractCommand.executeHelper(AbstractCommand.java:205)
	at org.jboss.pnc.bacon.pig.Pig.execute(Pig.java:115)
	at org.aesh.command.impl.operator.EndOperator.execute(EndOperator.java:41)
	at org.aesh.command.impl.Executions.execute(Executions.java:213)
	at org.aesh.command.impl.AeshCommandRuntime.executeCommand(AeshCommandRuntime.java:161)
	at org.jboss.pnc.bacon.cli.App.run(App.java:97)
	at org.jboss.pnc.bacon.cli.App.main(App.java:128)
Caused by: org.apache.http.client.ClientProtocolException: null
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:187)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
	at org.jboss.pnc.bacon.pig.impl.utils.FileDownloadUtils.downloadWithClient(FileDownloadUtils.java:106)
	at org.jboss.pnc.bacon.pig.impl.utils.FileDownloadUtils.downloadTo(FileDownloadUtils.java:90)
	... 19 common frames omitted
Caused by: org.apache.http.ProtocolException: Target host is not specified
	at org.apache.http.impl.conn.DefaultRoutePlanner.determineRoute(DefaultRoutePlanner.java:71)
	at org.apache.http.impl.client.InternalHttpClient.determineRoute(InternalHttpClient.java:125)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	... 23 common frames omitted
```

**Comment by thescouser89** [comment]
Fixed! There was a typo on the indy url to return when temporary. Also added a test to make sure we don't return null.
