### ISSUE TITLE
Pig hangs during license generation

### ISSUE THREAD

**Issue by djcoleman** [project-ncl/bacon#358]
I'm running the following command to generate licenses for an existing repository:
`$ bacon pig run -v --skipPncUpdate --skipBuilds --skipJavadoc --skipSharedContent  --skipSources --skipRepo --repoZip tmp/repository.zip -o --profile stage $config_dir`

The last few lines of the log are:
```
[DEBUG] - Requesting: GET http://orch-stage.DOMAIN:null/pnc-rest/v2/build-configs/2325/builds?sort=%3Ddesc%3DsubmitTime&pageSize=50&pageIndex=0&q=status%3D%3DSUCCESS%3BtemporaryBuild%3D%3Dfalse&latest=false&running=false Headers: Accept:[application/json].
[DEBUG] - Requesting: GET http://orch-stage.DOMAIN:null/pnc-rest/v2/builds/14412/logs/build Headers: .
[DEBUG] - Requesting: GET http://orch-stage.DOMAIN:null/pnc-rest/v2/builds/14416/logs/build Headers: .
[DEBUG] - Requesting: GET http://orch-stage.DOMAIN:null/pnc-rest/v2/builds/14067/logs/build Headers: .
[DEBUG] - Loading first page.
[DEBUG] - Loading first page.
[DEBUG] - Requesting: GET http://orch-stage.DOMAIN:null/pnc-rest/v2/builds/14416/artifacts/built?pageSize=50&pageIndex=0 Headers: Accept:[application/json].
[DEBUG] - Requesting: GET http://orch-stage.DOMAIN:null/pnc-rest/v2/builds/14412/artifacts/built?pageSize=50&pageIndex=0 Headers: Accept:[application/json].
```
Something after the last call to artifacts/built causes bacon to hang. Accessing the URL in the browser (with the ":null") removed works fine. 
I've attached the build-yaml.config file: [build-config.yaml.txt](https://github.com/project-ncl/bacon/files/5123143/build-config.yaml.txt)

**Comment by rnc** [comment]
@djcoleman Which version were you using please (ideally the -V output with the SHA).

**Comment by thescouser89** [comment]
I've noticed it too actually. It's strange how it only appeared lately for me. Please retry with the latest snapshot Darren.

I believe the issue was caused by an unclosed InputStream that caused this lock while trying to get the build logs. I don't understand why an unclosed InputStream would create such a lock though. Please retry the latest snapshot and let me know!

**Comment by djcoleman** [comment]
I updated to revision 30c493e1, but now getting a different error:
```
[DEBUG] - Loading first page.
[DEBUG] - Requesting: GET http://orch-stage.DOMAIN:null/pnc-rest/v2/group-configs/648/group-builds?sort=%3Ddesc%3DsubmitTime&pageSize=50&pageIndex=0&q=temporaryBuild%3D%3Dfalse Headers: Accept:[application/json].
[ERROR] - Something wrong happened: 
java.lang.RuntimeException: Cannot get list of group builds for group configuration 648
	at org.jboss.pnc.bacon.pig.impl.pnc.BuildInfoCollector.getBuildsFromLatestGroupConfiguration(BuildInfoCollector.java:166)
	at org.jboss.pnc.bacon.pig.PigFacade.getBuilds(PigFacade.java:364)
	at org.jboss.pnc.bacon.pig.PigFacade.run(PigFacade.java:133)
	at org.jboss.pnc.bacon.pig.Pig$Run.doExecute(Pig.java:247)
	at org.jboss.pnc.bacon.pig.Pig$Run.doExecute(Pig.java:137)
	at org.jboss.pnc.bacon.pig.Pig$PigCommand.lambda$execute$0(Pig.java:128)
	at org.jboss.pnc.bacon.common.cli.AbstractCommand.executeHelper(AbstractCommand.java:212)
	at org.jboss.pnc.bacon.pig.Pig$PigCommand.execute(Pig.java:116)
	at org.aesh.command.impl.operator.EndOperator.execute(EndOperator.java:41)
	at org.aesh.command.impl.Executions$ExecutionImpl.execute(Executions.java:213)
	at org.jboss.pnc.bacon.cli.App.run(App.java:114)
	at org.jboss.pnc.bacon.cli.App.main(App.java:168)
[DEBUG] - Stacktrace
java.lang.RuntimeException: Cannot get list of group builds for group configuration 648
	at org.jboss.pnc.bacon.pig.impl.pnc.BuildInfoCollector.getBuildsFromLatestGroupConfiguration(BuildInfoCollector.java:166)
	at org.jboss.pnc.bacon.pig.PigFacade.getBuilds(PigFacade.java:364)
	at org.jboss.pnc.bacon.pig.PigFacade.run(PigFacade.java:133)
	at org.jboss.pnc.bacon.pig.Pig$Run.doExecute(Pig.java:247)
	at org.jboss.pnc.bacon.pig.Pig$Run.doExecute(Pig.java:137)
	at org.jboss.pnc.bacon.pig.Pig$PigCommand.lambda$execute$0(Pig.java:128)
	at org.jboss.pnc.bacon.common.cli.AbstractCommand.executeHelper(AbstractCommand.java:212)
	at org.jboss.pnc.bacon.pig.Pig$PigCommand.execute(Pig.java:116)
	at org.aesh.command.impl.operator.EndOperator.execute(EndOperator.java:41)
	at org.aesh.command.impl.Executions$ExecutionImpl.execute(Executions.java:213)
	at org.jboss.pnc.bacon.cli.App.run(App.java:114)
	at org.jboss.pnc.bacon.cli.App.main(App.java:168)
```
I think there is a problem with using submitTime in the sort parameter.

**Comment by jbartece** [comment]
Moved to  NCL-5987
